"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArmorsPassivesList = exports.ArmorsPassive = void 0;
var ArmorsPassive;
(function (ArmorsPassive) {
    ArmorsPassive["Eclaireur"] = "\u00C9claireur";
    ArmorsPassive["KitIngenieur"] = "Kit d'ing\u00E9nieur";
    ArmorsPassive["ConduitElectrique"] = "Conduit \u00E9lectrique";
    ArmorsPassive["ExplosifsIntegres"] = "Explosifs int\u00E9gr\u00E9s";
    ArmorsPassive["FiltrationAvancee"] = "Filtration avanc\u00E9e";
    ArmorsPassive["MemePasMal"] = "M\u00EAme pas mal";
    ArmorsPassive["PareAssaut"] = "Par\u00E9 \u00E0 l'assaut";
    ArmorsPassive["EpauletteRenforcee"] = "\u00C9paulettes renforc\u00E9es";
    ArmorsPassive["RembourrageBalistique"] = "Rembourrage balistique";
    ArmorsPassive["CommeRoc"] = "Comme un roc";
    ArmorsPassive["ConditionPhysiqueOptimale"] = "Condition physique optimale";
    ArmorsPassive["Inflammable"] = "Inflammable";
    ArmorsPassive["Acclimate"] = "Acclimat\u00E9";
    ArmorsPassive["PresenceFantome"] = "Pr\u00E9sence fant\u00F4me";
    ArmorsPassive["Rembourrage"] = "Rembourrage";
    ArmorsPassive["Hazmat"] = "Hazmat";
    ArmorsPassive["AssistanceMecanique"] = "Assistance m\u00E9canique";
    ArmorsPassive["ProtectionDemocratique"] = "Protection d\u00E9mocratique";
    ArmorsPassive["TrousseSoins"] = "Trousse de soins";
    ArmorsPassive["PasAssure"] = "Pas assur\u00E9";
    ArmorsPassive["RembourrageSupplementaire"] = "Rembourrage suppl\u00E9mentaire";
    ArmorsPassive["Pistolero"] = "Pistolero";
    ArmorsPassive["AdrenoDefibrilateur"] = "Adr\u00E9no-d\u00E9fibrilateur";
    ArmorsPassive["TempeteDesert"] = "Temp\u00EAte du d\u00E9sert";
    ArmorsPassive["Grenadier"] = "Grenadier";
    ArmorsPassive["ProtectionAmelioree"] = "Protection am\u00E9lior\u00E9e";
    ArmorsPassive["AffluxAdrenaline"] = "Afflux d'adr\u00E9naline";
    ArmorsPassive["Renforcement"] = "Renforcement";
})(ArmorsPassive || (exports.ArmorsPassive = ArmorsPassive = {}));
exports.ArmorsPassivesList = Object.values(ArmorsPassive);
